### ISSUE TITLE
Mark homework 1, exercise 1,2 of Weifeng-Zhu

### ISSUE THREAD

**Issue by ZhuWeifeng94** [ZhuWeifeng94/stat679work#1]

**Comment by ZhuWeifeng94** [comment]
@cecileane
The SHA: https://github.com/ZhuWeifeng94/stat679work/commit/080cdad3c043b3529923ee7251aa3327703c4b34
Hi, professor
In the directory hw1 are what I did. 
Thank you!
Weifeng Zhou

**Comment by cecileane** [comment]
Hi Weifeng,

Nice job. Feedback below:

Your `readme` files could be improved: the main one refers to homework 1, and the one in the `hw1` directory does not have practical information to reproduce the results. Your scripts have no comments.

Your script to normalize file names is elegant in its design. It would have been better, however, to use `timetest${i}_snaq.log` instead of `timetest$i\_snaq.log` (4 similar instances). Generally, it is good practice to access shell variables with `${i}` instead of `$i`.

Your result file is not in csv format (comma separate variables): spaces instead of commas are used to separate the columns.

When I ran your summary script, it did not work fully: I got a result file `summary_zwf.csv` with 32 lines, not 16 lines. That's because you only append to the file, so if you run the script 3 times total, then the result file has 3 times the same information.

You have a clever use of `cut` with various delimiters. Unfortunately, you did not get much practice with `grep` as a result. It was one of the main goals of this homework. None of your commands used _extended_ regular expressions. Learning to use extended regular expressions would be useful for all other languages, not just the shell.

You could also make your code more elegant by assigning fewer variables and using more pipes, like here:

``` shell
c=`echo ./log/$b\.log`
d=`grep 'hmax' $c | head -1 | cut -d ' ' -f 4 | cut -d , -f 1`
```

could be done with either one of these 2 options below (no need for the variable `c`):

``` shell
d=`echo ./log/$b\.log | grep 'hmax' | head -1 | cut -d ' ' -f 4 | cut -d , -f 1`
d=`grep 'hmax' ./log/$b\.log | head -1 | cut -d ' ' -f 4 | cut -d , -f 1`
```

final note: somehow you are tracking a file "newfile.py" in your repository.
