### ISSUE TITLE
Mark homework 1, exercise 3, of Weifeng-Zhu

### ISSUE THREAD

**Issue by ZhuWeifeng94** [ZhuWeifeng94/stat679work#3]
https://github.com/ZhuWeifeng94/stat679work/commit/035fdb8a88b6e2e6f3affb4c15919fc17adca72d
@cecileane
Hi, professor
I am really sorry that I saw the e-mail that you told me I haven't handed my homework. 
I really have finished it before the deadline, but I forgot to write the issue.
And this is my ex3 for hw1, which use sed a lot to get the information that I need.
Thank you!
Weifeng Zhou

**Comment by ZhuWeifeng94** [comment]
After reading result from others, I found some error from script before.
https://github.com/ZhuWeifeng94/stat679work/commit/58783ae7daed5953ae088135b45f428d19e827ca
And this is the one after modifying.

**Comment by ZhuWeifeng94** [comment]
https://github.com/ZhuWeifeng94/stat679work/commit/b1f12d9d61ae3683ec69556b867371b8bb6255ea
Also, I changed my readme file because after I read that from my classmates. I found my readme file is really poor, so I tried to make it better.

**Comment by cecileane** [comment]
Thanks Weifeng! This is my way of asking Alex (@ajschmidt01) and Huanwen (@huanwenwu) to try your script and provide feedback on it.

**Comment by huanwenwu** [comment]
Hi Weifeng,

Your code is successfully run in my computer, and your exercise fully meets professor’s requirement. What impresses me a lot is your “readme.md” file in your “hw1” directory. You describe your files in detail and lists all requirements of each exercise in a tidy format, and it makes readers feel so comfortable when reading your file. I think I should learn from you and improve my readme file in future exercises. Besides, your “sed” syntax is very concise and efficient, and you also comment your code clearly.

Here are some suggestions which may help you improve your code:
First, I think the variable names can be more specific. It would be better if you used names like “CPUtime”, “Nruns” instead of simple letters. It not only helps other readers understand your code better, but also helps you recall when you read your file in the future. 
Second, there are some problem of indent in your script. For instance, there is no need to have space before “do” when you use for loops. Though they do not cause error, but a tidy format dose make the code seem more beautiful. You can try the auto indent function by clicking “edit- lines- auto indent” in Atom. 
Overall, I think you did very well, and thanks for your sharing!

Huanwen

**Comment by ajschmidt01** [comment]
Hi Weifeng,

I ran your scripts, and everything functioned as intended. I particularly liked how you handled the under3460 variable creation.  In my script file, I created these variables by using a “sed” statement that restricted the output to variables under the threshold.  Your method of using if statements and counter variables was much cleaner.  

A few small suggestions: 
1. The readme file did a good job of describing each script, but the readme could use some more documentation, particularly in describing which files should be in the folder. For instance, based on the readme file, I wasn’t sure how the data files should be placed into the project folder. I needed to read the script files to determine that log and out folders had to be in the project folder. 
2. In addition, I think using more specific variable names (as opposed to a, b, c, etc.) would help the readability of the script file.  For example, using the column names (e.g., Cputime) as the variable names in the script would help clarify what each line is accomplishing. 
3. Similarly, a few more comments in the script file would also provide clarity for outside readers. For instance, when creating the counter variables (e.g., k1=0), it might be nice to comment that you are creating counter variables to add up the number of values under 3460. 

Nice job with the homework! I learned some tricks I will make use of in the future!
