### ISSUE TITLE
Mark homework2 Weifeng-Zhu

### ISSUE THREAD

**Issue by ZhuWeifeng94** [ZhuWeifeng94/stat679work#4]
https://github.com/ZhuWeifeng94/stat679work/commit/73a16a5a9cbad950b7e867fe24b9dd5f82b8c738
@cecileane 
Dear professor:
This is what I did for homework2. If there is something wrong, please let me know!
Thank you!

Bset,
Weifeng Zhu

**Comment by cecileane** [comment]
Hi Weifeng,

Nice job! Feedback below:

In your Markdown files (readme), remove the colon (`:`) for the links to work
as you expect. I put an example below. If you write this:
`[energy.csv]:(https://github.com/UWMadison-computingtools/coursedata/blob/master/hw2-datamerge/energy.csv)`
you get this:
[energy.csv]:(https://github.com/UWMadison-computingtools/coursedata/blob/master/hw2-datamerge/energy.csv)
But if you remove the colon and write this:
`[energy.csv](https://github.com/UWMadison-computingtools/coursedata/blob/master/hw2-datamerge/energy.csv)`
then you get this:
[energy.csv](https://github.com/UWMadison-computingtools/coursedata/blob/master/hw2-datamerge/energy.csv)

## running your script

You have a detailed explanation of how to use your script, in your readme file. Perfect! Unfortunately, the command usage should give the path to the script, path to input files etc.

It would be best if your script could check for errors. For example, it should check that it's given at least 2 arguments:

```shell
$ python scripts/hw2.py
Traceback (most recent call last):
  File "scripts/hw2.py", line 51, in <module>
    dataenergy = open(sys.argv[2])
IndexError: list index out of range
```

When I gave it 3 arguments, it returns an error saying that it needed 3 or 4 arguments:

```shell
$ python scripts/hw2.py data/waterTemperature.csv data/energy.csv myout.csv
Traceback (most recent call last):
  File "scripts/hw2.py", line 97, in <module>
    raise IOError("It can only take four or three arguments")
OSError: It can only take four or three arguments
```

If you had used the `argparse` library, it would have done all these checks correctly for you and would have output a helpful error message (saying that it needs an energy file and a temperature file, for instance).

When I ran your script, it looks like there is a missing new line after the header, when the output goes to the standard output (not a file):


```shell
$ python scripts/hw2.py data/waterTemperature.csv data/energy.csv
"#","Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)","Energy Produced (kWh)"1,07/29/16 10:26:34 AM,72.86,2.956
2,07/29/16 11:26:34 AM,73.92,
3,07/29/16 12:26:34 PM,73.98,
...
```

The difference of behavior between stdout and file output is because you did not embed this piece of code within a function: you did some copying and pasting on lines 87 and 93 (same code, except for file name versus stdout). Line 88 was not copy-pasted...

## about your code

You broke the problem down into a few functions, and you have helpful docstrings for your module and for your functions. Great!

In your script, your function `do_merging` has the keyword argument `re = sys.stdout`. This name `re` is not recommended: because it's the name of the module for regular expressions. Your don't use this module in this particular script, so it's not a problem, but it can lead to confusion for a human reader.
It is much better practice to use the `with` syntax to open a file (either for reading or writing), because it will get closed even if an error occurs with what you do with the file.

When you `raise Exception` (line 42), it's best to add an error message to your exception.

Your readme file for the script says that the algorithm was described elsewhere, but it is still good practice to add comments inside the code to explain a little about the algorithm, near that lines that do each step.

I like that you used different kinds of exceptions to raise different types of errors. You also check that the data are sorted in the energy file. I suspect that there is a typo in your `check` function, though, because this line has the same value repeated twice:

`if "".join(e[i+1][0].split(spl)) < "".join(e[i+1][0].split(spl)):`

so there would always be equality, and the function would never return an error (i.e. never detect that dates are not sorted).

Great job overall.

**Comment by cecileane** [comment]
One more comment: I believe that the energy value is written one line below where it should (just one hour late). For instance, instead of producing this:

    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.3,

your code produces this:

    14,07/29/16 11:26:34 PM,73.45,
    15,07/30/16 12:26:34 AM,72.3,9.468
